### ISSUE TITLE
keep -fork github.com/:org/:repo 명령어를 더 많이 사용하니까 이 줄을 먼저 설명하는건 어때요?

### ISSUE THREAD

**Issue by khw7096** [lazypic/keep#24]

**Comment by kybin** [comment]
점점 그냥 다운로드를 위해서도 많이 사용하게 될거에요. 그리고 기본 동작보다 인수를 넣었을때의 동작을 먼저 설명하는건 일반적이진 않은것 같아요.

**Comment by khw7096** [comment]
그냥 다운로드라면 `git clone` 이 워낙 유명하여.. 그렇게 생각해보았지만.. OK 예요.

**Comment by kybin** [comment]
한웅씨가 이미 닫았지만 설명하자면 포크를 쉽게 하는것보다 개발폴더를 일관성있게 관리하는것이 keep의 더 중요한 기능이라고 생각해서 그랬어요. 물론 처음에는 포크를 하는 툴로 만들어진것은 맞지만요.
