### ISSUE TITLE
-fork 옵션을 사용했을때 이미 해당 레포지터리가 포크되어있는 경우 알리기

### ISSUE THREAD

**Issue by kybin** [lazypic/keep#25]
해당 레포지터리가 이미 포크되어있을때와 그렇지 않을때 다운로드 받은 레포지터리의 내용이 달라지지만 사용자가 그걸 알 수 없으므로 혼란에 빠질수 있다.

**Comment by khw7096** [comment]
+2

**Comment by kybin** [comment]
fork를 따로 명령어로 빼면서 이제는 fork가 레포지터리 포크 및 remote를 추가하는 기능만 하기 때문에 더이상 유효하지 않은 문제이다. 닫음.
