### ISSUE TITLE
keep과 fork를 분리할 예정입니다.

### ISSUE THREAD

**Issue by kybin** [lazypic/keep#29]
keep은 현재 기능 중 소스 코드를 구조화된 위치에 다운로드 받는 역할만 하게 될 것이고
fork는 현재 레포지터리를 포크하는 기능만 가지게 될 겁니다. 

새로 생기는 fork는 upstream과 origin으로 구분하는 방식이 아니라 origin, user (예: kybin) 구분 방식이 될겁니다.

이렇게 바꾸는 이유는 여러 사용자가 함께 작업할 때 upstream, origin, user 처럼 나와 다른 사용자를 다르게 바라보는 방식에서 origin, user 처럼 나 또한 한 사람의 사용자로 바라보는 방식이 유닉스의 홈 디렉토리 관리에서 보듯이 더 낫다고 생각되기 때문입니다.

**Comment by khw7096** [comment]
- keep == download == git clone
- fork 는 포크만..

결국 keep, fork를 사용하는 본질은 둘다 경로정리인가요?

**Comment by kybin** [comment]
keep은 경로 정리, fork는 git remote 정리에요.

**Comment by kybin** [comment]
완료.
