### ISSUE TITLE
1차 Readme 작성후 영문 체크

### ISSUE THREAD

**Issue by khw7096** [lazypic/keep#3]

**Comment by baesy0** [comment]
![DCD093B5-D008-499B-A8F1-EA3BBCCF6C83](https://user-images.githubusercontent.com/40417084/68437891-bd2a9d00-0205-11ea-87f4-08c8bd0af81a.jpeg)
Keep은 소프트웨어 이름이니까 대문자로 시작하면 좋을거 같아요. 소문자로 시작하니까 매끄럽게 읽히지 않는 느낌입니당
- Keep
- KEEP
을 추천합니다.

**Comment by baesy0** [comment]
![BCC12BFA-D2DF-42A7-945A-B6A99F3790BF](https://user-images.githubusercontent.com/40417084/68437967-f7943a00-0205-11ea-8845-852281144dd9.jpeg)
여기는 문장이 잘 안읽혀요! 어떤 말을 하고 싶은거에요?

**Comment by khw7096** [comment]
그렇겠네요.. 사람들이 읽을때 keep 뜻으로 해석할 수 있으니까요.

**Comment by khw7096** [comment]
참고: 이미 keep 이라는 명령어가 존재하기는 하네요.

https://www.ostechnix.com/save-commands-terminal-use-demand/

**Comment by kybin** [comment]
소문자 keep이 이름이기 때문에 그대로 써주는게 좋다고 생각해요. 거기에 따른 약간의 혼란스러움은 사실 의도된것이기도 해요 ㅎㅎ

**Comment by kybin** [comment]
만일 그 대신 포크된 레포지터리를 다운로드 받고싶다면이라는 문장을 쓰려고 했어요~

**Comment by kybin** [comment]
@khw7096 이런 일반 명사 이름을 가진 명령어가 없을수는 없어서 용도가 겹치지만 않으면 될것 같아요

**Comment by khw7096** [comment]
Openpipelin.io에 올려서 전세계 사람들이 사용하기 위해서 고의적으로 만드는 “약간의 혼란스러움을 의도하고 만드는것”은 결국 사용자를 낮출것같아요. 다시 KEEP에 한표!

**Comment by kybin** [comment]
전 유저가 늘어나지 않아도 상관없는데.. 하지만 원한다면 Keep으로 바꾸는것은 괜찮아요.

**Comment by khw7096** [comment]
저도 유저가 늘어날 필요는 없지만, 고의적으로 막을 필요도 없다고 생각하여~!! Keep 로 가더라도 영문법상 모호한 점이 있을까요? Bailey?

**Comment by kybin** [comment]
참고로 명령어나 레포지터리 이름이 아니라 README에 사용되는 이름만 Keep으로 할 거에요.

**Comment by baesy0** [comment]
### keep / Keep
의도된 거였군요ㅋㅋㅋ
Keep정도만 되도 충분할 거 같아요. 개발자의 의도가 사라지는게 좀 안타깝지만ㅋㅋ
README는 쉬운 이해가 먼저니까!
명령어나 레포지터리 이름에는 keep을 그대로 쓰는 거에 대해서는 좋다고 생각해요

**Comment by baesy0** [comment]
> 만일 그 대신 포크된 레포지터리를 다운로드 받고싶다면이라는 문장을 쓰려고 했어요~

1. If you want to download the forked repo, do following.
1. If you want to download the forked repo instead, do following.
1. If you want to download the forked repo instead of original repo, do following.

첫 번째 문장은 가장 단순한 형태구요
두 번째 문장부터는 '그 대신'이라는 뉘앙스를 살려서 옮겨봤어요.
세 번째 문장은 두 번째 문장보다 의미를 좀 더 명확히 해주었어요

혹시 살리고 싶은 의도나 뉘앙스가 있다면 알려줘요!

**Comment by kybin** [comment]
너무 명확하면 재미없으니까 두번째로 가죠. ㅋㅋ

**Comment by khw7096** [comment]
2번 Go.
